# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ShoppingListNew' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShoppingListNew
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Kingfisher' , '~> 4.0'
pod ‘Firebase/Storage’
pod 'SVProgressHUD'

end
