# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiveSiteApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DiveSiteApp
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Kingfisher' , '~> 4.0'
pod ‘Firebase/Storage’
pod 'SVProgressHUD'
pod 'SwiftyJSON'

end
